# Generated by Django 5.1.4 on 2026-05-13 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WineNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(db_index=True, max_length=200, verbose_name='생산자')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='와인명')),
                ('vintage', models.CharField(blank=True, max_length=10, verbose_name='빈티지')),
                ('color', models.CharField(choices=[('red', '레드'), ('white', '화이트'), ('rosé', '로제'), ('sparkling', '스파클링'), ('dessert', '디저트'), ('fortified', '주정강화'), ('orange', '오렌지')], db_index=True, max_length=20, verbose_name='색상')),
                ('region', models.CharField(blank=True, max_length=200, verbose_name='지역')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='국가')),
                ('grape', models.CharField(blank=True, max_length=200, verbose_name='포도 품종')),
                ('appearance', models.TextField(blank=True, verbose_name='외관')),
                ('nose', models.JSONField(default=list, verbose_name='향 (Nose)')),
                ('palate', models.JSONField(default=list, verbose_name='맛 (Palate)')),
                ('finish', models.TextField(blank=True, verbose_name='여운 (Finish)')),
                ('my_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='내 평점')),
                ('vivino_rating', models.CharField(blank=True, max_length=10, verbose_name='Vivino 평점')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='구매 가격')),
                ('currency', models.CharField(default='KRW', max_length=10, verbose_name='통화')),
                ('purchase_location', models.CharField(blank=True, max_length=200, verbose_name='구매 장소')),
                ('wine_searcher_price', models.CharField(blank=True, max_length=50, verbose_name='Wine-Searcher 가격')),
                ('food_pairing', models.JSONField(default=list, verbose_name='음식 페어링')),
                ('photos', models.JSONField(default=list, verbose_name='사진')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('date_tasted', models.DateField(blank=True, db_index=True, null=True, verbose_name='시음 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '와인 노트',
                'verbose_name_plural': '와인 노트 목록',
                'ordering': ['-date_tasted', '-created_at'],
            },
        ),
    ]
